### ISSUE TITLE
`Methods` section in roxygen docs malformed

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/generics#43]
In my package, I am extracting a list of available `S3` tidy methods using `generics` template:

https://github.com/IndrajeetPatil/broomExtra/blob/56292a0fca15cd18df605c32b1f8e6d041813f25/R/generics.R#L17-L18

But, as can be seen from the webpage, this is not properly formatted:
https://indrajeetpatil.github.io/broomExtra/reference/tidy.html#methods

![image](https://user-images.githubusercontent.com/11330453/62826015-ac28ac00-bb82-11e9-8b4e-3aed11fc7476.png)

Any ideas on how to fix this?

**Comment by IndrajeetPatil** [comment]
cc @alexpghayes 

Not sure if the same issue is also observed for `broom` - it has been a while since `broom`'s website was updated.

**Comment by alexpghayes** [comment]
`generics` does some fancy dynamic documentation stuff that is over my head. @DavisVaughan should know more. But I don't think this is a `broom` issue.

Also, the automatic pkgdown is up and running so the web documentation now matches `master`!

**Comment by IndrajeetPatil** [comment]
@DavisVaughan Any thoughts on why this might be so?

**Comment by DavisVaughan** [comment]
Why are you shimming over `tidy()`? I'd imagine that method dispatch should "just work" and will call the right method from the right package as is (broom or broom.mixed). If it doesn't work for some reason, there's probably a PR to broom/broom.mixed that should be made to fix it. I'd rather that all work correctly rather than shimming over `tidy()` and making it not a non-generic.
